"""Tests for https://adventofcode.com/2023/day/15 Puzzles."""

import unittest
from crt import CRT
class TestCRT(unittest.TestCase):

    puzzle_input_a = ["noop",
                      "addx 3",
                      "addx -5",]
    puzzle_input_b = ["addx 15",
                      "addx -11",
                      "addx 6",
                      "addx -3",
                      "addx 5",
                      "addx -1",
                      "addx -8",
                      "addx 13",
                      "addx 4",
                      "noop",
                      "addx -1",
                      "addx 5",
                      "addx -1",
                      "addx 5",
                      "addx -1",
                      "addx 5",
                      "addx -1",
                      "addx 5",
                      "addx -1",
                      "addx -35",
                      "addx 1",
                      "addx 24",
                      "addx -19",
                      "addx 1",
                      "addx 16",
                      "addx -11",
                      "noop",
                      "noop",
                      "addx 21",
                      "addx -15",
                      "noop",
                      "noop",
                      "addx -3",
                      "addx 9",
                      "addx 1",
                      "addx -3",
                      "addx 8",
                      "addx 1",
                      "addx 5",
                      "noop",
                      "noop",
                      "noop",
                      "noop",
                      "noop",
                      "addx -36",
                      "noop",
                      "addx 1",
                      "addx 7",
                      "noop",
                      "noop",
                      "noop",
                      "addx 2",
                      "addx 6",
                      "noop",
                      "noop",
                      "noop",
                      "noop",
                      "noop",
                      "addx 1",
                      "noop",
                      "noop",
                      "addx 7",
                      "addx 1",
                      "noop",
                      "addx -13",
                      "addx 13",
                      "addx 7",
                      "noop",
                      "addx 1",
                      "addx -33",
                      "noop",
                      "noop",
                      "noop",
                      "addx 2",
                      "noop",
                      "noop",
                      "noop",
                      "addx 8",
                      "noop",
                      "addx -1",
                      "addx 2",
                      "addx 1",
                      "noop",
                      "addx 17",
                      "addx -9",
                      "addx 1",
                      "addx 1",
                      "addx -3",
                      "addx 11",
                      "noop",
                      "noop",
                      "addx 1",
                      "noop",
                      "addx 1",
                      "noop",
                      "noop",
                      "addx -13",
                      "addx -19",
                      "addx 1",
                      "addx 3",
                      "addx 26",
                      "addx -30",
                      "addx 12",
                      "addx -1",
                      "addx 3",
                      "addx 1",
                      "noop",
                      "noop",
                      "noop",
                      "addx -9",
                      "addx 18",
                      "addx 1",
                      "addx 2",
                      "noop",
                      "noop",
                      "addx 9",
                      "noop",
                      "noop",
                      "noop",
                      "addx -1",
                      "addx 2",
                      "addx -37",
                      "addx 1",
                      "addx 3",
                      "noop",
                      "addx 15",
                      "addx -21",
                      "addx 22",
                      "addx -6",
                      "addx 1",
                      "noop",
                      "addx 2",
                      "addx 1",
                      "noop",
                      "addx -10",
                      "noop",
                      "noop",
                      "addx 20",
                      "addx 1",
                      "addx 2",
                      "addx 2",
                      "addx -6",
                      "addx -11",
                      "noop",
                      "noop",
                      "noop",]
    
    def test_part_one(self):
        crt = CRT(self.puzzle_input_a, cycle_monitor=[1,2,3,4,5])
        expected_result = 9
        crt.execute_instructions()
        expected_result = [1,1,4,4,-1]
        self.assertEqual(crt.signal_strengths(), expected_result)
        expected_result = 13140
        self.assertEqual(crt.sum_signal_strength(), expected_result)

        crt = CRT(self.puzzle_input_a, cycle_monitor=[20,40,60,100,140,180,220])
        crt.execute_instructions()
        expected_result = [420,1140,1800,2940,2880,3960]
        self.assertEqual(crt.signal_strengths(), expected_result)
        expected_result = 13140
        self.assertEqual(crt.sum_signal_strengths(), expected_result)

    
    def test_part_two(self):
        pass